#!/bin/bash

lookup() {
  local ip name
  ip=$1; shift

  # Try ssh and telnet in parallel.
  name=$({ ssh_name "${ip}" & telnet_name "${ip}" & wait; } | head -n 1)
  printf "%s %s\n" "${ip}" "${name}"
}

ssh_name() {
  local ip
  ip=$1; shift

  timeout 5 ssh "${ip}" "hostname" 2>/dev/null
}

telnet_name() {
  local ip
  ip=$1; shift

  {
    sleep 1
    echo root
    sleep 1
    echo "cat /tmp/knight/opt/config/thing.json"
    sleep 1
  } \
    | timeout 5 telnet "${ip}" 2>/dev/null \
    | awk -F '[[:space:]"]+' '/thing_name/ { print $4 }'
}

PREV=
while true; do
  # Match wg configs that were last seen less than x minutes ago
  CUR=$(
    ssh wireguard "sudo wg show all dump" \
      | awk -v "cutoff=$(($(date +%s) - 300))" '$6 > cutoff { print $5 }'
  )

  # Only check new configs.
  DIFF=$(comm -1 -3 <(sort <<<"$PREV") <(sort <<<"$CUR"))
  for cidr in $DIFF; do
    lookup "${cidr%%/*}" &
  done

  PREV=$CUR
  sleep 2
done
