#!/bin/bash

LOOKUP_TIMEOUT=10

lookup() {
  local ip name
  ip=$1; shift

  # Try ssh and telnet in parallel.
  name=$({ ssh_name "${ip}" & telnet_name "${ip}" & wait; } | head -n 1)
  printf "%s %s\n" "${ip}" "${name}"
}

ssh_name() {
  local ip
  ip=$1; shift

  timeout $LOOKUP_TIMEOUT ssh "${ip}" "hostname" 2>/dev/null
}

telnet_name() {
  local ip
  ip=$1; shift

  {
    sleep $((LOOKUP_TIMEOUT / 2))
    echo root
    sleep 2
    echo "cat /tmp/knight/opt/config/thing.json /tmp/knight/factory/opt/config/thing.json /tmp/knight/update/opt/config/thing.json"
    sleep 2
  } \
    | timeout $LOOKUP_TIMEOUT telnet "${ip}" 2>/dev/null \
    | awk -F '[[:space:]"]+' '/thing_name/ { print $4 }'
}

if command -v expect >/dev/null 2>&1; then
  LOOKUP_TIMEOUT=5

  telnet_name() {
    local ip
    ip=$1; shift

    expect -c "
      set timeout 3
      spawn timeout $LOOKUP_TIMEOUT telnet ${ip}
      expect \"login:\"
      send \"root\n\"
      expect \"#\"
      send \"cat /tmp/knight/opt/config/thing.json /tmp/knight/factory/opt/config/thing.json /tmp/knight/update/opt/config/thing.json\n\"
      expect \"}\"
      " 2>/dev/null \
      | awk -F '[[:space:]"]+' '/thing_name/ { print $4 }'
  }
fi

PREV=
while true; do
  # Match wg configs that were last seen less than x minutes ago
  CUR=$(
    ssh wireguard "sudo wg show all dump" \
      | awk -v "cutoff=$(($(date +%s) - 300))" '$6 > cutoff { print $5 }'
  )

  # Only check new configs.
  DIFF=$(comm -1 -3 <(sort <<<"$PREV") <(sort <<<"$CUR"))
  for cidr in $DIFF; do
    lookup "${cidr%%/*}" &
    #sleep 1
  done

  PREV=$CUR
  sleep 5
done
